@startuml
left to right direction

actor "Admin" as fc
actor "Learner" as br

rectangle SchoolCommunityPlatform {
  usecase "Events Crud" as UC1
  usecase "Approve or Remove Users from Communities" as UC2
  usecase "Communities Crud" as UC3
  usecase "View and Edit Profile" as UC4
  usecase "Browse Communities" as UC5
  usecase "Join Community" as UC6
}

fc -- UC1
fc -- UC2
fc -- UC3
br -- UC4
br -- UC5
br -- UC6

@enduml
